### ISSUE TITLE
安装速度很慢并且安装中途会失败

### ISSUE THREAD

**Issue by dayingwy** [macacajs/macaca-electron#14]
安装命令：npm install -g macaca-electron
使用该命令进行安装的时候下载速度很慢，并且会安装失败，实际上网速度很快

**Comment by meowtec** [comment]
配置 npm 源：https://registry.npm.taobao.org/ 和 electron 源： https://npm.taobao.org/mirrors/electron/

**Comment by meowtec** [comment]
npm 源就不说了，网上都有。
electron 源配置环境变量：

```
ELECTRON_MIRROR=https://npm.taobao.org/mirrors/electron/
```
