### ISSUE TITLE
多任务问题

### ISSUE THREAD

**Issue by Milesssssss** [macacajs/macaca-electron#15]
在程序中期望多余一个测试案例同时在跑，

比如使用 
    let electron1 = new Electron();
    let electron2 = new Electron();
    let electron3 = new Electron();

结果是只能跑一个程序，剩下的要么报错

Timeout: Wait for message from the runner TIMEOUT.

要么没有响应。

求解答

**Comment by meowtec** [comment]
原因是 ELectron 在 OSX 里不能同时开多个应用进程
