### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by 82318179** [macacajs/macaca-electron#48]
![22](https://user-images.githubusercontent.com/25976728/74100740-f5c37500-4b6c-11ea-9a4e-78a2866263ce.jpg)
按照demo 来截图 百度 首页 报错如上

**Comment by 82318179** [comment]
`const fs = require('fs');
const path = require('path');
const Electron = require('macaca-electron');

const electron = new Electron();

/**
  default options
  {
    show: true,
    alwaysOnTop: false,
    x: 0,
    y: 0,
    width: 800,
    height: 600,
    userAgent: 'userAgent string',
    webPreferences: {
      nodeIntegration: false
    }
  }
*/
var m = async () => {
  await electron.startDevice({
    show: false // in silence
  });

  await electron.maximize();
  await electron.setWindowSize(null, 500, 500);
  await electron.get('https://www.baidu.com');
  // yield driver.get('https://www.baidu.com', { preserveCookies: true });
  const imgData = await electron.getScreenshot();
  const img = new Buffer(imgData, 'base64');
  const p = path.join(__dirname, '..', 'screenshot.png')
  fs.writeFileSync(p, img.toString('binary'), 'binary');
  console.log(`screenshot: ${p}`);

  await electron.stopDevice();
};
m();`

this demo error also

**Comment by 82318179** [comment]
`const fs = require('fs');
const path = require('path');
const Electron = require('macaca-electron');

const electron = new Electron();

/**
  default options
  {
    show: true,
    alwaysOnTop: false,
    x: 0,
    y: 0,
    width: 800,
    height: 600,
    userAgent: 'userAgent string',
    webPreferences: {
      nodeIntegration: false
    }
  }
*/
let m = async () => {
  await electron.startDevice({
    show: false // in silence
  });

  await electron.maximize();
  await electron.setWindowSize(null, 500, 500);
  await electron.get('https://www.baidu.com');
  // yield driver.get('https://www.baidu.com', { preserveCookies: true });
  const imgData = await electron.getScreenshot();
  const img = new Buffer(imgData, 'base64');
  const p = path.join(__dirname, '..', 'screenshot.png')
  fs.writeFileSync(p, img.toString('binary'), 'binary');
  console.log(`screenshot: ${p}`);

  await electron.stopDevice();
};
m();`
The latest demo code also error 

`[Running] node "e:\newlu\macaca-electron-screenshot-master\lib\macaca-electron-screenshot.js"
(node:2324) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:2324) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
    at Function.from (buffer.js:305:9)
    at new Buffer (buffer.js:265:17)
    at m (e:\newlu\macaca-electron-screenshot-master\lib\macaca-electron-screenshot.js:32:15)
(node:2324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by xudafeng** [comment]
@82318179 

https://github.com/macacajs/macaca-electron/blob/master/README.md#standalone-usage

按照readme运行即可
